-- 2.
 Create educational email templates for the new sequences
-- ═══════════════════════════════════════════════════════════════════════════
INSERT INTO public.email_templates (slug, name, subject, html_body, text_body, is_active)
VALUES
  ('getting_started', 'Getting Started', 'Getting started with BTCMiner.online',
   '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"></head><body style="margin:0;padding:0;background:#0a0a0a;font-family:-apple-system,BlinkMacSystemFont,''Segoe UI'',Roboto,sans-serif;"><table width="100%" cellpadding="0" cellspacing="0" style="background:#0a0a0a;padding:32px 16px;"><tr><td align="center"><table width="560" cellpadding="0" cellspacing="0" style="background:#111827;border-radius:12px;overflow:hidden;border:1px solid #1f2937;max-width:560px;width:100%;"><tr><td style="background:linear-gradient(135deg,#1a1a2e 0%,#16213e 60%,#0f3460 100%);padding:32px 28px;text-align:center;"><h1 style="margin:0;color:#f1f5f9;font-size:22px;font-weight:700;">Getting Started</h1></td></tr><tr><td style="padding:32px 28px 24px;"><p style="margin:0 0 16px;color:#94a3b8;font-size:15px;line-height:1.6;">Hi {{first_name}},</p><p style="margin:0 0 24px;color:#94a3b8;font-size:15px;line-height:1.6;">Your account is verified. Here are the three simple steps to start earning Bitcoin:</p><ol style="margin:0 0 24px;color:#94a3b8;font-size:15px;line-height:1.6;"><li>Make your first deposit into your BTCMiner wallet.</li><li>Choose a mining contract that matches your goals.</li><li>Watch your dashboard for real-time mining rewards.</li></ol><p style="margin:0 0 24px;color:#94a3b8;font-size:15px;line-height:1.6;">Your 10% welcome discount is still active and will be applied automatically at checkout.</p><table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:28px;"><tr><td align="center"><a href="{{dashboard_link}}" style="display:inline-block;background:#f7931a;color:#000000;font-weight:700;font-size:16px;text-decoration:none;padding:15px 48px;border-radius:8px;">Go to Dashboard</a></td></tr></table></td></tr></table></td></tr></table></body></html>',
   'Hi {{first_name}},\n\nYour account is verified. Here are the three simple steps to start earning Bitcoin:\n1. Make your first deposit.\n2. Choose a mining contract.\n3. Watch your dashboard for real-time rewards.\n\nYour 10% welcome discount is still active.\n\nDashboard: {{dashboard_link}}', true),
  ('how_cloud_mining_works', 'How Cloud Mining Works', 'How cloud mining works',
   '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"></head><body style="margin:0;padding:0;background:#0a0a0a;font-family:-apple-system,BlinkMacSystemFont,''Segoe UI'',Roboto,sans-serif;"><table width="100%" cellpadding="0" cellspacing="0" style="background:#0a0a0a;padding:32px 16px;"><tr><td align="center"><table width="560" cellpadding="0" cellspacing="0" style="background:#111827;border-radius:12px;overflow:hidden;border:1px solid #1f2937;max-width:560px;width:100%;"><tr><td style="background:linear-gradient(135deg,#1a1a2e 0%,#16213e 60%,#0f3460 100%);padding:32px 28px;text-align:center;"><h1 style="margin:0;color:#f1f5f9;font-size:22px;font-weight:700;">How Cloud Mining Works</h1></td></tr><tr><td style="padding:32px 28px 24px;"><p style="margin:0 0 16px;color:#94a3b8;font-size:15px;line-height:1.6;">Hi {{first_name}},</p><p style="margin:0 0 16px;color:#94a3b8;font-size:15px;line-height:1.6;">Cloud mining lets you rent mining hardware hosted in professional data centers. You earn a share of the Bitcoin mined without managing physical machines.</p><p style="margin:0 0 24px;color:#94a3b8;font-size:15px;line-height:1.6;">Your 10% welcome discount is still active and will be applied automatically.</p><table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:28px;"><tr><td align="center"><a href="{{dashboard_link}}" style="display:inline-block;background:#f7931a;color:#000000;font-weight:700;font-size:16px;text-decoration:none;padding:15px 48px;border-radius:8px;">Explore Contracts</a></td></tr></table></td></tr></table></td></tr></table></body></html>',
   'Hi {{first_name}},\n\nCloud mining lets you rent mining hardware hosted in professional data centers. You earn a share of the Bitcoin mined without managing physical machines.\n\nYour 10% welcome discount is still active.\n\nExplore contracts: {{dashboard_link}}', true),
  ('choosing_contract', 'Choosing a Mining Contract', 'Choosing a mining contract that fits you',
   '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"></head><body style="margin:0;padding:0;background:#0a0a0a;font-family:-apple-system,BlinkMacSystemFont,''Segoe UI'',Roboto,sans-serif;"><table width="100%" cellpadding="0" cellspacing="0" style="background:#0a0a0a;padding:32px 16px;"><tr><td align="center"><table width="560" cellpadding="0" cellspacing="0" style="background:#111827;border-radius:12px;overflow:hidden;border:1px solid #1f2937;max-width:560px;width:100%;"><tr><td style="background:linear-gradient(135deg,#1a1a2e 0%,#16213e 60%,#0f3460 100%);padding:32px 28px;text-align:center;"><h1 style="margin:0;color:#f1f5f9;font-size:22px;font-weight:700;">Choosing a Mining Contract</h1></td></tr><tr><td style="padding:32px 28px 24px;"><p style="margin:0 0 16px;color:#94a3b8;font-size:15px;line-height:1.6;">Hi {{first_name}},</p><p style="margin:0 0 16px;color:#94a3b8;font-size:15px;line-height:1.6;">Pick a contract based on your budget and goals. Contracts vary by hashrate, duration, and maintenance fee. All costs are transparent before checkout.</p><p style="margin:0 0 24px;color:#94a3b8;font-size:15px;line-height:1.6;">Your 10% welcome discount is still active and will be applied automatically.</p><table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:28px;"><tr><td align="center"><a href="{{dashboard_link}}" style="display:inline-block;background:#f7931a;color:#000000;font-weight:700;font-size:16px;text-decoration:none;padding:15px 48px;border-radius:8px;">View Contracts</a></td></tr></table></td></tr></table></td></tr></table></body></html>',
   'Hi {{first_name}},\n\nPick a contract based on your budget and goals. All costs are transparent before checkout.\n\nYour 10% welcome discount is still active.\n\nView contracts: {{dashboard_link}}', true),
  ('current_mining_opportunities', 'Current Mining Opportunities', 'Current mining opportunities',
   '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"></head><body style="margin:0;padding:0;background:#0a0a0a;font-family:-apple-system,BlinkMacSystemFont,''Segoe UI'',Roboto,sans-serif;"><table width="100%" cellpadding="0" cellspacing="0" style="background:#0a0a0a;padding:32px 16px;"><tr><td align="center"><table width="560" cellpadding="0" cellspacing="0" style="background:#111827;border-radius:12px;overflow:hidden;border:1px solid #1f2937;max-width:560px;width:100%;"><tr><td style="background:linear-gradient(135deg,#1a1a2e 0%,#16213e 60%,#0f3460 100%);padding:32px 28px;text-align:center;"><h1 style="margin:0;color:#f1f5f9;font-size:22px;font-weight:700;">Current Mining Opportunities</h1></td></tr><tr><td style="padding:32px 28px 24px;"><p style="margin:0 0 16px;color:#94a3b8;font-size:15px;line-height:1.6;">Hi {{first_name}},</p><p style="margin:0 0 16px;color:#94a3b8;font-size:15px;line-height:1.6;">Now is a great time to start mining. Check the marketplace for available contracts and live hashrate pricing.</p><p style="margin:0 0 24px;color:#94a3b8;font-size:15px;line-height:1.6;">Your 10% welcome discount is still active and will be applied automatically.</p><table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:28px;"><tr><td align="center"><a href="{{dashboard_link}}" style="display:inline-block;background:#f7931a;color:#000000;font-weight:700;font-size:16px;text-decoration:none;padding:15px 48px;border-radius:8px;">Browse Marketplace</a></td></tr></table></td></tr></table></td></tr></table></body></html>',
   'Hi {{first_name}},\n\nNow is a great time to start mining. Check the marketplace for available contracts and live hashrate pricing.\n\nYour 10% welcome discount is still active.\n\nBrowse marketplace: {{dashboard_link}}', true),
  ('how_to_buy_contract', 'How to Buy a Mining Contract', 'How to buy your first mining contract',
   '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"></head><body style="margin:0;padding:0;background:#0a0a0a;font-family:-apple-system,BlinkMacSystemFont,''Segoe UI'',Roboto,sans-serif;"><table width="100%" cellpadding="0" cellspacing="0" style="background:#0a0a0a;padding:32px 16px;"><tr><td align="center"><table width="560" cellpadding="0" cellspacing="0" style="background:#111827;border-radius:12px;overflow:hidden;border:1px solid #1f2937;max-width:560px;width:100%;"><tr><td style="background:linear-gradient(135deg,#1a1a2e 0%,#16213e 60%,#0f3460 100%);padding:32px 28px;text-align:center;"><h1 style="margin:0;color:#f1f5f9;font-size:22px;font-weight:700;">How to Buy a Mining Contract</h1></td></tr><tr><td style="padding:32px 28px 24px;"><p style="margin:0 0 16px;color:#94a3b8;font-size:15px;line-height:1.6;">Hi {{first_name}},</p><p style="margin:0 0 16px;color:#94a3b8;font-size:15px;line-height:1.6;">You have a deposit ready. Buying a contract is easy:</p><ol style="margin:0 0 24px;color:#94a3b8;font-size:15px;line-height:1.6;"><li>Go to the Marketplace.</li><li>Choose a contract and click Buy.</li><li>Review your 10% welcome discount applied automatically.</li><li>Confirm your purchase.</li></ol><table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:28px;"><tr><td align="center"><a href="{{dashboard_link}}" style="display:inline-block;background:#f7931a;color:#000000;font-weight:700;font-size:16px;text-decoration:none;padding:15px 48px;border-radius:8px;">Buy a Contract</a></td></tr></table></td></tr></table></td></tr></table></body></html>',
   'Hi {{first_name}},\n\nYou have a deposit ready. Buying a contract is easy:\n1. Go to the Marketplace.\n2. Choose a contract.\n3. Your 10% welcome discount is applied automatically.\n4. Confirm.\n\nBuy a contract: {{dashboard_link}}', true),
  ('available_contracts', 'Available Contracts', 'Available mining contracts today',
   '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"></head><body style="margin:0;padding:0;background:#0a0a0a;font-family:-apple-system,BlinkMacSystemFont,''Segoe UI'',Roboto,sans-serif;"><table width="100%" cellpadding="0" cellspacing="0" style="background:#0a0a0a;padding:32px 16px;"><tr><td align="center"><table width="560" cellpadding="0" cellspacing="0" style="background:#111827;border-radius:12px;overflow:hidden;border:1px solid #1f2937;max-width:560px;width:100%;"><tr><td style="background:linear-gradient(135deg,#1a1a2e 0%,#16213e 60%,#0f3460 100%);padding:32px 28px;text-align:center;"><h1 style="margin:0;color:#f1f5f9;font-size:22px;font-weight:700;">Available Mining Contracts</h1></td></tr><tr><td style="padding:32px 28px 24px;"><p style="margin:0 0 16px;color:#94a3b8;font-size:15px;line-height:1.6;">Hi {{first_name}},</p><p style="margin:0 0 24px;color:#94a3b8;font-size:15px;line-height:1.6;">Browse the current selection of cloud mining contracts. Your 10% welcome discount is automatically applied at checkout.</p><table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:28px;"><tr><td align="center"><a href="{{dashboard_link}}" style="display:inline-block;background:#f7931a;color:#000000;font-weight:700;font-size:16px;text-decoration:none;padding:15px 48px;border-radius:8px;">View Contracts</a></td></tr></table></td></tr></table></td></tr></table></body></html>',
   'Hi {{first_name}},\n\nBrowse the current selection of cloud mining contracts. Your 10% welcome discount is automatically applied at checkout.\n\nView contracts: {{dashboard_link}}', true),
  ('mining_pools', 'Mining Pools', 'Our mining pools',
   '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"></head><body style="margin:0;padding:0;background:#0a0a0a;font-family:-apple-system,BlinkMacSystemFont,''Segoe UI'',Roboto,sans-serif;"><table width="100%" cellpadding="0" cellspacing="0" style="background:#0a0a0a;padding:32px 16px;"><tr><td align="center"><table width="560" cellpadding="0" cellspacing="0" style="background:#111827;border-radius:12px;overflow:hidden;border:1px solid #1f2937;max-width:560px;width:100%;"><tr><td style="background:linear-gradient(135deg,#1a1a2e 0%,#16213e 60%,#0f3460 100%);padding:32px 28px;text-align:center;"><h1 style="margin:0;color:#f1f5f9;font-size:22px;font-weight:700;">Our Mining Pools</h1></td></tr><tr><td style="padding:32px 28px 24px;"><p style="margin:0 0 16px;color:#94a3b8;font-size:15px;line-height:1.6;">Hi {{first_name}},</p><p style="margin:0 0 24px;color:#94a3b8;font-size:15px;line-height:1.6;">BTCMiner partners with reliable mining pools to provide consistent payouts and transparent performance. Your 10% welcome discount is still active.</p><table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:28px;"><tr><td align="center"><a href="{{dashboard_link}}" style="display:inline-block;background:#f7931a;color:#000000;font-weight:700;font-size:16px;text-decoration:none;padding:15px 48px;border-radius:8px;">Go to Dashboard</a></td></tr></table></td></tr></table></td></tr></table></body></html>',
   'Hi {{first_name}},\n\nBTCMiner partners with reliable mining pools to provide consistent payouts and transparent performance. Your 10% welcome discount is still active.\n\nDashboard: {{dashboard_link}}', true),
  ('mining_farms', 'Mining Farms', 'Our transparent mining farms',
   '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"></head><body style="margin:0;padding:0;background:#0a0a0a;font-family:-apple-system,BlinkMacSystemFont,''Segoe UI'',Roboto,sans-serif;"><table width="100%" cellpadding="0" cellspacing="0" style="background:#0a0a0a;padding:32px 16px;"><tr><td align="center"><table width="560" cellpadding="0" cellspacing="0" style="background:#111827;border-radius:12px;overflow:hidden;border:1px solid #1f2937;max-width:560px;width:100%;"><tr><td style="background:linear-gradient(135deg,#1a1a2e 0%,#16213e 60%,#0f3460 100%);padding:32px 28px;text-align:center;"><h1 style="margin:0;color:#f1f5f9;font-size:22px;font-weight:700;">Our Mining Farms</h1></td></tr><tr><td style="padding:32px 28px 24px;"><p style="margin:0 0 16px;color:#94a3b8;font-size:15px;line-height:1.6;">Hi {{first_name}},</p><p style="margin:0 0 24px;color:#94a3b8;font-size:15px;line-height:1.6;">Our infrastructure is hosted in enterprise-grade facilities with reliable uptime, cooling, and security. Your 10% welcome discount is still active.</p><table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:28px;"><tr><td align="center"><a href="{{dashboard_link}}" style="display:inline-block;background:#f7931a;color:#000000;font-weight:700;font-size:16px;text-decoration:none;padding:15px 48px;border-radius:8px;">Start Mining Now</a></td></tr></table></td></tr></table></td></tr></table></body></html>',
   'Hi {{first_name}},\n\nOur infrastructure is hosted in enterprise-grade facilities with reliable uptime, cooling, and security. Your 10% welcome discount is still active.\n\nStart mining: {{dashboard_link}}', true)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  subject = EXCLUDED.subject,
  html_body = EXCLUDED.html_body,
  text_body = EXCLUDED.text_body,
  is_active = EXCLUDED.is_active,
  updated_at = now();

-- ═══════════════════════════════════════════════════════════════════════════
