
-- Marketplace stats (dynamically configurable)
CREATE TABLE marketplace_stats (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text UNIQUE NOT NULL,
  value text NOT NULL,
  label text,
  sort_order int NOT NULL DEFAULT 0,
  updated_at timestamptz DEFAULT now()
);
ALTER TABLE marketplace_stats ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public_read_marketplace_stats" ON marketplace_stats FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "admin_all_marketplace_stats" ON marketplace_stats FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Marketplace content blocks
CREATE TABLE marketplace_content (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text UNIQUE NOT NULL,
  title text,
  body text NOT NULL,
  visible boolean NOT NULL DEFAULT true,
  sort_order int NOT NULL DEFAULT 0,
  updated_at timestamptz DEFAULT now()
);
ALTER TABLE marketplace_content ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public_read_marketplace_content" ON marketplace_content FOR SELECT TO anon, authenticated USING (visible = true);
CREATE POLICY "admin_all_marketplace_content" ON marketplace_content FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Marketplace FAQ (separate from site-wide FAQ)
CREATE TABLE marketplace_faq (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  question text NOT NULL,
  answer text NOT NULL,
  sort_order int NOT NULL DEFAULT 0,
  visible boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE marketplace_faq ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public_read_marketplace_faq" ON marketplace_faq FOR SELECT TO anon, authenticated USING (visible = true);
CREATE POLICY "admin_all_marketplace_faq" ON marketplace_faq FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Marketplace internal SEO links
CREATE TABLE marketplace_links (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  anchor_text text NOT NULL,
  target_url text NOT NULL,
  description text,
  sort_order int NOT NULL DEFAULT 0,
  visible boolean NOT NULL DEFAULT true
);
ALTER TABLE marketplace_links ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public_read_marketplace_links" ON marketplace_links FOR SELECT TO anon, authenticated USING (visible = true);
CREATE POLICY "admin_all_marketplace_links" ON marketplace_links FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Seed marketplace stats
INSERT INTO marketplace_stats (key, value, label, sort_order) VALUES
  ('total_hashrate_sold',  '2.4 EH/s',    'Total Hashrate Sold',       1),
  ('active_contracts',     '18,432',      'Active Mining Contracts',   2),
  ('total_btc_mined',      '1,284.7 BTC', 'Total BTC Mined',           3),
  ('avg_daily_payout',     '0.000312 BTC','Average Daily Payout',      4),
  ('marketplace_volume',   '$142M+',      'Marketplace Volume',        5),
  ('active_buyers',        '26,800+',     'Active Buyers',             6);

-- Seed marketplace content blocks
INSERT INTO marketplace_content (key, title, body, sort_order) VALUES
(
  'intro',
  'Hashrate Marketplace',
  E'## What Is a Hashrate Marketplace?\n\nA hashrate marketplace is a platform where individuals and institutions can purchase mining power — measured in terahashes per second (TH/s) or petahashes per second (PH/s) — directly from professional mining operations without needing to own, operate, or maintain physical hardware.\n\nAt BTCMiner.online, our hashrate marketplace connects buyers with real ASIC mining hardware deployed across our enterprise data centers in Iceland, Texas, Kazakhstan, and Paraguay. When you purchase a mining contract, you receive a proportional share of the Bitcoin block rewards generated by the hardware running your allocated hashrate.\n\n## How Bitcoin Mining Contracts Work\n\nA Bitcoin mining contract is a digital agreement that grants you access to a specific amount of computational power (hashrate) for a defined period. Here is how the process works from purchase to payout:\n\n**Step 1 — Select Your Contract**: Browse available hashrate packages ranging from 100 TH/s starter contracts to multi-petahash industrial plans. Each contract specifies the algorithm (SHA-256 for Bitcoin), the hashrate amount, contract duration, and maintenance fee.\n\n**Step 2 — Fund Your Wallet**: Deposit Bitcoin, Litecoin, USDT, or other supported cryptocurrencies to your BTCMiner.online wallet.\n\n**Step 3 — Purchase Hashrate**: Complete the purchase. Your hashrate allocation becomes active within minutes and is immediately assigned to our mining pools.\n\n**Step 4 — Earn Daily Rewards**: Mining rewards are calculated and distributed to your wallet every 24 hours based on your proportional contribution to the total pool hashrate.\n\n## How Mining Rewards Are Generated\n\nBitcoin mining rewards come from two sources: the block subsidy (currently 3.125 BTC per block after the 2024 halving) and transaction fees collected from users broadcasting Bitcoin transactions. Approximately 144 blocks are mined every 24 hours, generating a predictable daily reward pool that is distributed among all miners proportionally to their hashrate contribution.\n\nYour estimated daily earnings follow this formula:\n\n**Daily BTC = (Your TH/s ÷ Total Network TH/s) × 144 × Block Reward − Maintenance Fees**\n\n## How Network Difficulty Affects Earnings\n\nBitcoin''s mining difficulty adjusts every 2,016 blocks (approximately every two weeks) to ensure new blocks are found every 10 minutes on average. When more miners join the network and total hashrate increases, difficulty rises and per-unit earnings decrease. When hashrate falls, difficulty drops and per-unit earnings increase.\n\nBTCMiner.online displays real-time difficulty data directly on the marketplace so you can make informed purchasing decisions. Our mining profit calculator uses live difficulty data to provide accurate earnings estimates.\n\n## Benefits of Buying Hashrate vs. Operating Physical Hardware\n\nOwning and operating ASIC mining hardware involves substantial capital expenditure, electricity costs, cooling infrastructure, maintenance overhead, and technical expertise. Our hashrate marketplace eliminates all of these barriers:\n\n- **No upfront hardware purchase**: Contract prices are a fraction of ASIC hardware costs\n- **No electricity setup**: Power costs are bundled into the maintenance fee\n- **No technical expertise required**: We manage firmware, overclocking, pool configuration, and repairs\n- **Immediate mining start**: Contracts activate within minutes of purchase\n- **Scalable positions**: Add hashrate incrementally without logistics constraints\n- **No obsolescence risk**: We upgrade hardware fleets as newer generations release\n\n## How BTCMiner.online Manages Mining Infrastructure\n\nOur operations team manages over 555 MW of mining capacity across four continents. Each facility features redundant power systems, enterprise-grade cooling (air cooling and immersion cooling), 24/7 on-site technicians, and direct fiber connections to major mining pools. We publish live farm statistics, hardware inventory, and mining pool performance data in our Transparency Center so you can verify operations independently.',
  1
),
(
  'how_contracts_work',
  'How Bitcoin Mining Contracts Work',
  E'When you purchase a mining contract at BTCMiner.online, you gain ownership of a defined hashrate allocation running on our physical ASIC hardware. Your contract specifies the exact TH/s or PH/s of computing power assigned to your account, the mining algorithm (SHA-256 for Bitcoin), the contract duration in days, and a daily maintenance fee denominated in USD per TH/s.\n\nMining rewards are credited to your wallet every 24 hours. Contract duration begins at the moment of purchase. At expiry, you may choose to purchase a new contract or withdraw your accumulated rewards.',
  2
),
(
  'sha256_mining',
  'Understanding SHA-256 Mining',
  E'SHA-256 (Secure Hash Algorithm 256-bit) is the proof-of-work algorithm that secures the Bitcoin blockchain. Mining hardware performs billions of SHA-256 hash computations per second in search of a valid block hash that meets the current difficulty target.\n\nModern SHA-256 ASICs such as the Bitmain Antminer S21 XP and MicroBT Whatsminer M60 deliver 270–300 TH/s while consuming approximately 20–21 joules per terahash, making them the most efficient Bitcoin mining hardware available. BTCMiner.online''s hardware fleet is continuously upgraded to ensure optimal energy efficiency and maximum reward output.',
  3
),
(
  'reward_calculation',
  'How Mining Rewards Are Calculated',
  E'Your daily Bitcoin earnings are determined by four variables: your allocated hashrate, the total Bitcoin network hashrate, the current block reward, and the prevailing network difficulty.\n\nThe calculation formula is: **Daily BTC = (Your TH/s ÷ Network TH/s) × 144 blocks × 3.125 BTC − Maintenance Fee**\n\nAs network hashrate grows (more miners joining), your proportional share decreases and daily earnings adjust accordingly. Our profit calculator uses live API data from public blockchain sources to display real-time earnings estimates before you make any purchase.',
  4
),
(
  'why_marketplace',
  'Why Use a Hashrate Marketplace',
  E'The BTCMiner.online Hashrate Marketplace offers the most accessible path to Bitcoin mining income without the complexity and capital requirements of self-hosted operations.\n\n**Lower startup costs**: Entry-level contracts start at 100 TH/s — equipment that would cost $2,000–$4,000 at retail ASIC prices.\n\n**No hardware maintenance**: Firmware updates, hardware repairs, and pool reconfigurations are handled entirely by our operations team.\n\n**Immediate mining access**: Contracts activate within minutes. No shipping delays, customs clearance, or installation time.\n\n**Scalable mining capacity**: Purchase additional contracts at any time to compound your mining position proportionally.',
  5
);

-- Seed marketplace FAQ
INSERT INTO marketplace_faq (question, answer, sort_order) VALUES
  ('What is a mining contract?', 'A mining contract is a hashrate purchase agreement that gives you access to a defined amount of Bitcoin mining power (measured in TH/s or PH/s) running on real ASIC hardware in our data centers. You receive daily Bitcoin rewards proportional to your hashrate allocation for the duration of the contract.', 1),
  ('How do payouts work?', 'Mining rewards are calculated every 24 hours based on your hashrate contribution to the pool. Net rewards (gross mining output minus daily maintenance fees) are automatically credited to your BTCMiner.online wallet. You can withdraw to any external Bitcoin address at any time above the minimum withdrawal threshold.', 2),
  ('How are rewards calculated?', 'Your daily BTC earnings = (Your TH/s ÷ Total Network TH/s) × 144 blocks × Current Block Reward − Daily Maintenance Fee. Our profit calculator uses live network difficulty and BTC price data to display real-time estimates before you purchase.', 3),
  ('What affects mining profitability?', 'The primary variables are: Bitcoin network hashrate and difficulty (adjusts every ~2 weeks), Bitcoin price, block reward (currently 3.125 BTC per block after the April 2024 halving), and your contract''s maintenance fee. Higher network difficulty reduces per-unit earnings; higher BTC price increases USD-denominated returns.', 4),
  ('What happens when a contract expires?', 'When a mining contract reaches its end date, the hashrate allocation is deactivated and no further rewards are generated. All accumulated rewards remain in your wallet. You can purchase a new contract at any time to continue mining.', 5),
  ('Can I purchase multiple contracts?', 'Yes. There is no limit on the number of contracts you can hold simultaneously. Purchasing multiple contracts increases your total hashrate allocation and daily reward output proportionally. You can combine different algorithm contracts to diversify across Bitcoin, Litecoin, and Kaspa.', 6),
  ('Are earnings guaranteed?', 'No. Mining output depends on Bitcoin network conditions including difficulty, hashrate, block reward, and BTC price — all of which fluctuate. We display real-time profitability estimates based on current data, but past performance does not guarantee future results. Please review our Risk Disclosure before purchasing.', 7),
  ('How often are rewards distributed?', 'Rewards are calculated and distributed every 24 hours. The distribution window runs from 00:00 UTC to 23:59 UTC. You will see the reward credit appear in your wallet transaction history each day your contract is active.', 8);

-- Seed internal SEO links
INSERT INTO marketplace_links (anchor_text, target_url, description, sort_order) VALUES
  ('Bitcoin Mining Calculator',      '/calculator',    'Calculate your estimated earnings before purchasing', 1),
  ('Mining Farms',                   '/farms',         'View our enterprise mining facilities worldwide',     2),
  ('ASIC Hardware Fleet',            '/hardware',      'See the mining hardware running your contracts',      3),
  ('Bitcoin Mining Difficulty Guide','/blog',          'Understand how difficulty affects your earnings',     4),
  ('What Is Hashrate?',              '/blog',          'Learn about hashrate and how it is measured',         5),
  ('SHA-256 Mining Explained',       '/blog',          'Deep dive into the SHA-256 proof-of-work algorithm',  6),
  ('Mining Profitability Guide',     '/calculator',    'Guide to understanding and maximising profitability', 7);
